name: Run Python Script

on:
  schedule:
    - cron: '0 16 * * *'  # 根据 UTC 时间，调整到本地午夜 0 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python scripts/aaa/test2.py  # 运行 Python 脚本，确保脚本生成正确的 .m3u 文件

      - name: Force update file timestamps
        run: |
          touch scripts/aaa/*.m3u

      - name: Check for generated files
        run: |
          ls -la scripts/aaa/  # 列出目录中的所有文件，确认 M3U 文件是否存在

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add scripts/aaa/playlisty.m3u  # 只添加生成的 .m3u 文件
          git commit -m "Update M3U files" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
