name: Run Test1 Script  # 更改工作流的名称

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0 * * *'  # 每天午夜12:30（UTC）触发工作流
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Clean up old specific files
      run: |
        rm -f scripts/aaa/combined1.txt
        rm -f scripts/aaa/cleaned_combined1.txt
        rm -f scripts/aaa/playlisty.m3u

    - name: Run script
      run: |
        python scripts/aaa/test1.py  # 运行 test1.py 脚本

    - name: Check for generated files
      run: |
        ls -la scripts/aaa/  # 列出目录中的所有文件，确认文件生成情况
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       git config --global user.name 'github-actions'
       git config --global user.email 'github-actions@github.com'
       git config --global --add safe.directory /github/workspace
       git add scripts/aaa/combined1.txt scripts/aaa/cleaned_combined1.txt scripts/aaa/playlisty.m3u  # 确保添加文件
       git commit -m "Update M3U files" || echo "No changes to commit"
       git push || echo "Nothing to
